### ISSUE TITLE
SS4 upgrade?

### ISSUE THREAD

**Issue by adrian-stein** [tractorcow/silverstripe-campaignmonitor#14]
Hi,

Is this going to get an SS4 upgrade?

Thanks

**Comment by tractorcow** [comment]
I'm probably not going to implement it myself, but if someone were to make a go at it I'd review and merge it.

**Comment by tractorcow** [comment]
Looks like it was done with https://github.com/tractorcow/silverstripe-campaignmonitor/pull/13!
